version: '3' #wersja 3

services:
  nginx: 
    image: nginx:latest
    ports:
      - 6666:80 # dostęp poprzez port 6666
    volumes:
      - ./php:/app #podłączenie katalogu, aby wyświetlić jego zawartość
      - ./nginx:/etc/nginx/conf.d #podłączenie konfiguracji nginx
    networks:
      - backend-net #sieć backend
      - frontend-net #sieć frontend
    depends_on:
      - php  #zależnośc od kontenera php

  php:
    image: php:8.0-fpm
    volumes:
      - ./php:/app #podłączenie katalogu, aby wyświetlić jego zawartość
    networks:
      - backend-net #sieć backend

  mysql:
    image: mysql:latest
    environment:
        MYSQL_USER: 'user' #nazwa użytkownika
        MYSQL_PASSWORD: 'password' #hasło użytkownika
        MYSQL_ROOT_PASSWORD: 'root' #hasło roota
        MYSQL_DATABASE: 'testDB' #nazwa bazy
    volumes:
      - 'DBvolume:/var/lib/mysql' #podłączenie wolumenu dla bazy danych
    networks:
      - backend-net #sieć backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports: 
      - 6001:80 # dostęp poprzez port 6001
    links:
      - 'mysql:db' #wskazanie linku do bazy danych
    depends_on:
      - mysql #zależnośc od kontenera mysql
    networks:
      - backend-net #sieć backend

networks:
  backend-net: #sieć backend
  frontend-net: #sieć frontend

volumes:
  DBvolume: #inicjalizacji wolumenu dla bazy danych
